//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMailSender.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFSmtp
    {
        public int SmtpId { get; set; }
        public string Name { get; set; }
        public string Server { get; set; }
        public int Port { get; set; }
    }
}
